CREATE TABLE IF NOT EXISTS pets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  especie VARCHAR(50) NOT NULL,
  raca VARCHAR(50) DEFAULT 'SRD',
  idade INT NULL,
  peso DECIMAL(5,2) NULL,
  tutor_nome VARCHAR(100) NOT NULL,
  tutor_contato VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
